# Generated by Django 3.1.6 on 2021-04-05 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NSS_site', '0002_volunteer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='time_of_request',
            new_name='signup_time',
        ),
    ]
